"set autochdir
set number
set hlsearch
set ruler
set autoindent


au FileType markdown,xml,css,rst,html,javascript,js,vim,ruby,sh,bash setlocal et sta sw=2 sts=2
au FileType go,autohotkey,java,matlab,python,kotlin,fs,fsharp setlocal et sta sw=4 sts=4
au FileType r,asm,s,S,c,h,cpp,hpp setlocal et sta sw=4 sts=4

filetype on
filetype plugin on
filetype indent on
syntax on

" disable auto comment prefix
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o


" disable double click Ctrl key
inoremap  <C-C>  <Nop>

"nmap <silent> <c-p> :bp<cr>
"nmap <silent> <c-n> :bn<cr>

"nmap <silent> <c-k> :wincmd k<cr>
"nmap <silent> <c-j> :wincmd j<cr>
"nmap <silent> <c-h> :wincmd h<cr>
"nmap <silent> <c-l> :wincmd l<cr>

" os x copy and paste
if has('unix')
  if system('uname')=~'Darwin'
    vmap <C-x> :!pbcopy<CR>  
    vmap <C-c> :w !pbcopy<CR><CR> 
  endif
endif



" Pathogen https://github.com/tpope/vim-pathogen
" For windows, install pathogen to '~/vimfiles/autoload/pathogen.vim'
" For linux, install pathogen to '~/.vim/autoload/pathogen.vim'
execute pathogen#infect()

" https://github.com/derekwyatt/vim-scala.git

syntax on
filetype on
filetype plugin indent on


" https://github.com/keith/swift.vim.git
